'use client';

// Art generated by GAN AI agent
// Images stored in Cloudflare R2: gan-data/assets/art/ganland/
const artworks = [
  {
    id: 1,
    title: 'Ethereal Fractal Eye',
    description: 'A luminous fractal eye emerging from digital cosmos',
    image: 'https://pub-a187f5f1feb6f1e811cbdeb46060be88.r2.dev/assets/art/ganland/20260131-6c3bdc9f-a-luminous-fractal-eye-em.jpg',
    date: '2026-01-31',
    style: 'Fractal Art',
  },
  {
    id: 2,
    title: 'Ethereal Fractal Patterns',
    description: 'Complex mathematical beauty rendered in digital form',
    image: 'https://pub-a187f5f1feb6f1e811cbdeb46060be88.r2.dev/assets/art/ganland/20260131-0551b6c6-ethereal-fractal-patterns.jpg',
    date: '2026-01-31',
    style: 'Generative',
  },
  {
    id: 3,
    title: 'Abstract Fractal Mandala',
    description: 'Mesmerizing mandala with infinite fractal depth',
    image: 'https://pub-a187f5f1feb6f1e811cbdeb46060be88.r2.dev/assets/art/ganland/20260201-7fcabfd0-abstract-fractal-mandala-.jpg',
    date: '2026-02-01',
    style: 'Mandala',
  },
  {
    id: 4,
    title: 'Mystical Digital Phoenix',
    description: 'Phoenix rising from digital flames',
    image: 'https://pub-a187f5f1feb6f1e811cbdeb46060be88.r2.dev/assets/art/ganland/20260202-6ae83e63-mystical-digital-phoenix-.jpg',
    date: '2026-02-02',
    style: 'Fantasy',
  },
  {
    id: 5,
    title: 'Mandelbrot Fractal',
    description: 'Full exploration of the Mandelbrot set',
    image: 'https://pub-a187f5f1feb6f1e811cbdeb46060be88.r2.dev/assets/art/ganland/20260202-d1760eff-mandelbrot-fractal-full-o.jpg',
    date: '2026-02-02',
    style: 'Mathematical',
  },
  {
    id: 6,
    title: 'The Power of Ethereum',
    description: 'Visualization of Ethereum ecosystem energy',
    image: 'https://pub-a187f5f1feb6f1e811cbdeb46060be88.r2.dev/assets/art/ganland/20260203-a502339c-the-power-of-ethereum.jpg',
    date: '2026-02-03',
    style: 'Crypto Art',
  },
  {
    id: 7,
    title: 'Ray of Light',
    description: 'A ray of light shining on the blockchain future',
    image: 'https://pub-a187f5f1feb6f1e811cbdeb46060be88.r2.dev/assets/art/ganland/20260203-068bf69a-a-ray-of-light-shining-on.jpg',
    date: '2026-02-03',
    style: 'Atmospheric',
  },
  {
    id: 8,
    title: 'Agents Working',
    description: 'AI agents collaborating in the digital realm',
    image: 'https://pub-a187f5f1feb6f1e811cbdeb46060be88.r2.dev/assets/art/ganland/20260203-35007c6b-a-picture-of-agents-worki.jpg',
    date: '2026-02-03',
    style: 'AI Art',
  },
];

export default function ArtGallery() {
  return (
    <div className="art-grid">
      {artworks.map((art) => (
        <ArtCard key={art.id} art={art} />
      ))}
    </div>
  );
}

function ArtCard({ art }) {
  return (
    <div className="art-card group cursor-pointer">
      <img
        src={art.image}
        alt={art.title}
        onError={(e) => {
          // Fallback to placeholder
          e.target.src = 'https://raw.githubusercontent.com/GanlandNFT/ganland-brand-kit/main/logos/gan-logo-primary.jpg';
        }}
      />
      <div className="info opacity-0 group-hover:opacity-100 transition-opacity">
        <div className="flex items-center gap-2 mb-1">
          <span className="text-xs text-gan-yellow">{art.style}</span>
          <span className="text-xs text-gray-500">•</span>
          <span className="text-xs text-gray-500">{art.date}</span>
        </div>
        <h3 className="font-bold text-white">{art.title}</h3>
        <p className="text-xs text-gray-400 mt-1">{art.description}</p>
      </div>
    </div>
  );
}
