'use client';

// Art generated by GAN AI agent
// Images pinned to IPFS via Pinata
const artworks = [
  {
    id: 1,
    title: 'Ethereal Fractal Eye',
    description: 'A luminous fractal eye emerging from digital cosmos',
    image: 'https://gateway.pinata.cloud/ipfs/QmRoRPrJ4Ug5SHZwuvZd1e3xuk9zPHGKWUGRKBGXEmycGd',
    date: '2026-01-31',
    style: 'Fractal Art',
  },
  {
    id: 2,
    title: 'Ethereal Fractal Patterns',
    description: 'Complex mathematical beauty rendered in digital form',
    image: 'https://gateway.pinata.cloud/ipfs/QmZQciTn5couMFC3ELRYWU8Fydruo3uAWS9h2exxmj3H32',
    date: '2026-01-31',
    style: 'Generative',
  },
  {
    id: 3,
    title: 'Abstract Fractal Mandala',
    description: 'Mesmerizing mandala with infinite fractal depth',
    image: 'https://gateway.pinata.cloud/ipfs/QmbHn6zB1PbkKqoLRxDabsnjy1Busu2GATevJ4rMewgKrA',
    date: '2026-02-01',
    style: 'Mandala',
  },
  {
    id: 4,
    title: 'Mystical Digital Phoenix',
    description: 'Phoenix rising from digital flames',
    image: 'https://gateway.pinata.cloud/ipfs/QmZ9XTBDVyJ8mFjxc1o9UUrHashhafaSvuemCvZHCWdmHS',
    date: '2026-02-02',
    style: 'Fantasy',
  },
  {
    id: 5,
    title: 'Mandelbrot Fractal',
    description: 'Full exploration of the Mandelbrot set',
    image: 'https://gateway.pinata.cloud/ipfs/QmXCoZPAr4vtFNFYQsekjKQxmGaDnmbY4svanpCexwSLYV',
    date: '2026-02-02',
    style: 'Mathematical',
  },
  {
    id: 6,
    title: 'The Power of Ethereum',
    description: 'Visualization of Ethereum ecosystem energy',
    image: 'https://gateway.pinata.cloud/ipfs/QmazQoeikjFk4EqsmCaG6gaF4SEFvEaciXWGRosDzPH5jA',
    date: '2026-02-03',
    style: 'Crypto Art',
  },
  {
    id: 7,
    title: 'Ray of Light',
    description: 'A ray of light shining on the blockchain future',
    image: 'https://gateway.pinata.cloud/ipfs/QmQxLSNzVmYa78bkWnErZoJmMdsNhzi5ggMZuzBn7oNQE4',
    date: '2026-02-03',
    style: 'Atmospheric',
  },
  {
    id: 8,
    title: 'Agents Working',
    description: 'AI agents collaborating in the digital realm',
    image: 'https://gateway.pinata.cloud/ipfs/QmQnxpDLhv8BEYaWUtXnqvQFmbJ2XdUMR3YPcMTqFAYaa1',
    date: '2026-02-03',
    style: 'AI Art',
  },
];

export default function ArtGallery() {
  return (
    <div className="art-grid">
      {artworks.map((art) => (
        <ArtCard key={art.id} art={art} />
      ))}
    </div>
  );
}

function ArtCard({ art }) {
  return (
    <div className="art-card group cursor-pointer">
      <img
        src={art.image}
        alt={art.title}
        onError={(e) => {
          // Fallback to placeholder
          e.target.src = 'https://raw.githubusercontent.com/GanlandNFT/ganland-brand-kit/main/logos/gan-logo-primary.jpg';
        }}
      />
      <div className="info opacity-0 group-hover:opacity-100 transition-opacity">
        <div className="flex items-center gap-2 mb-1">
          <span className="text-xs text-gan-yellow">{art.style}</span>
          <span className="text-xs text-gray-500">•</span>
          <span className="text-xs text-gray-500">{art.date}</span>
        </div>
        <h3 className="font-bold text-white">{art.title}</h3>
        <p className="text-xs text-gray-400 mt-1">{art.description}</p>
      </div>
    </div>
  );
}
