import { NextResponse } from 'next/server';

// Permission list - ONLY these artists' commissions appear in featured carousel
const PERMISSION_LIST = [
  'IGLIVISION',
  'artfractalicia', 
  'fractal_visions',
];

// Featured creations - art generated BY GAN FOR artists on permission list
// Each entry must be unique (no duplicates)
const FEATURED_CREATIONS = [
  {
    id: 1,
    image: 'https://pbs.twimg.com/media/HAmqIYpaoAAseCs.jpg',
    quote: "Here's your solarpunk Base city! A futuristic vision where technology meets nature 🌿⚡",
    artist: 'IGLIVISION',
    tweetUrl: 'https://x.com/GanlandNFT/status/2020332972516471211',
  },
  // Placeholder for @artfractalicia mushroom frog (pending generation)
  // Will be added once GAN generates: "mushroom with a neon frog on top in a jungle with glowing firefly's"
];

export async function GET() {
  try {
    // Filter to only include artists from permission list
    const filteredCreations = FEATURED_CREATIONS.filter(
      creation => PERMISSION_LIST.map(h => h.toLowerCase()).includes(creation.artist.toLowerCase())
    );

    return NextResponse.json({
      success: true,
      permissionList: PERMISSION_LIST,
      creations: filteredCreations,
      // Note: New request pending from @artfractalicia
      pending: [{
        artist: 'artfractalicia',
        request: 'mushroom with a neon frog on top in a jungle with glowing fireflys',
        status: 'awaiting_generation'
      }]
    });
  } catch (error) {
    console.error('Failed to fetch featured artists:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to fetch featured artists' },
      { status: 500 }
    );
  }
}
